import 'package:get_it/get_it.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'core/security/encryption_service.dart';
import 'core/security/secure_storage_service.dart';
import 'core/network/api_client.dart';
import 'data/datasources/remote/auth_remote_datasource.dart';
import 'data/datasources/remote/family_remote_datasource.dart';
import 'data/datasources/remote/child_remote_datasource.dart';
import 'data/datasources/remote/location_remote_datasource.dart';
import 'data/datasources/remote/chat_remote_datasource.dart';
import 'data/datasources/remote/call_remote_datasource.dart';
import 'data/datasources/remote/device_remote_datasource.dart';
import 'data/datasources/local/local_storage_datasource.dart';
import 'data/repositories/auth_repository_impl.dart';
import 'data/repositories/family_repository_impl.dart';
import 'data/repositories/child_repository_impl.dart';
import 'data/repositories/location_repository_impl.dart';
import 'data/repositories/chat_repository_impl.dart';
import 'data/repositories/call_repository_impl.dart';
import 'data/repositories/device_repository_impl.dart';
import 'domain/repositories/auth_repository.dart';
import 'domain/repositories/family_repository.dart';
import 'domain/repositories/child_repository.dart';
import 'domain/repositories/location_repository.dart';
import 'domain/repositories/chat_repository.dart';
import 'domain/repositories/call_repository.dart';
import 'domain/repositories/device_repository.dart';

final getIt = GetIt.instance;

Future<void> configureDependencies() async {
  getIt.registerLazySingleton<FirebaseAuth>(() => FirebaseAuth.instance);
  getIt.registerLazySingleton<FirebaseFirestore>(() => FirebaseFirestore.instance);
  getIt.registerLazySingleton<FirebaseDatabase>(() => FirebaseDatabase.instance);
  getIt.registerLazySingleton<FirebaseStorage>(() => FirebaseStorage.instance);
  getIt.registerLazySingleton<FirebaseMessaging>(() => FirebaseMessaging.instance);
  getIt.registerLazySingleton<SecureStorageService>(() => SecureStorageService());
  getIt.registerLazySingleton<EncryptionService>(() => EncryptionService(getIt<SecureStorageService>()));
  getIt.registerLazySingleton<ApiClient>(() => ApiClient());
  getIt.registerLazySingleton<LocalStorageDatasource>(() => LocalStorageDatasource());
  getIt.registerLazySingleton<AuthRemoteDatasource>(() => AuthRemoteDatasource(firebaseAuth: getIt<FirebaseAuth>(), firebaseFirestore: getIt<FirebaseFirestore>(), firebaseMessaging: getIt<FirebaseMessaging>()));
  getIt.registerLazySingleton<FamilyRemoteDatasource>(() => FamilyRemoteDatasource(getIt<FirebaseFirestore>()));
  getIt.registerLazySingleton<ChildRemoteDatasource>(() => ChildRemoteDatasource(getIt<FirebaseFirestore>()));
  getIt.registerLazySingleton<LocationRemoteDatasource>(() => LocationRemoteDatasource(getIt<FirebaseDatabase>()));
  getIt.registerLazySingleton<ChatRemoteDatasource>(() => ChatRemoteDatasource(getIt<FirebaseFirestore>()));
  getIt.registerLazySingleton<CallRemoteDatasource>(() => CallRemoteDatasource(getIt<FirebaseFirestore>(), getIt<FirebaseDatabase>()));
  getIt.registerLazySingleton<DeviceRemoteDatasource>(() => DeviceRemoteDatasource(getIt<FirebaseFirestore>()));
  getIt.registerLazySingleton<AuthRepository>(() => AuthRepositoryImpl(authRemoteDatasource: getIt<AuthRemoteDatasource>(), localStorageDatasource: getIt<LocalStorageDatasource>(), encryptionService: getIt<EncryptionService>()));
  getIt.registerLazySingleton<FamilyRepository>(() => FamilyRepositoryImpl(familyRemoteDatasource: getIt<FamilyRemoteDatasource>()));
  getIt.registerLazySingleton<ChildRepository>(() => ChildRepositoryImpl(childRemoteDatasource: getIt<ChildRemoteDatasource>()));
  getIt.registerLazySingleton<LocationRepository>(() => LocationRepositoryImpl(locationRemoteDatasource: getIt<LocationRemoteDatasource>()));
  getIt.registerLazySingleton<ChatRepository>(() => ChatRepositoryImpl(chatRemoteDatasource: getIt<ChatRemoteDatasource>()));
  getIt.registerLazySingleton<CallRepository>(() => CallRepositoryImpl(callRemoteDatasource: getIt<CallRemoteDatasource>()));
  getIt.registerLazySingleton<DeviceRepository>(() => DeviceRepositoryImpl(deviceRemoteDatasource: getIt<DeviceRemoteDatasource>()));
}
